docs: add first draft of docs
StoryShop/app pull request #122
Opened 2016-09-26 19:12 UTC by sethmerrick

2016-09-26 20:01 UTC, joshdmiller commented on docs/getting_started_guide.md
> +A few things you should review before getting started:
Let's make these links.

2016-09-26 20:02 UTC, joshdmiller commented on docs/getting_started_guide.md
> +// src/../characters/items/index.js
These `..` are confusing because they have semantic meaning in file paths. I think the only missing part of the path is "components", right?

2016-09-26 20:05 UTC, joshdmiller commented on docs/getting_started_guide.md
> +      // 'charactersById', '1234', 'items', { from: 0, to: items.length }, [ '_id', 'name' ]
This comment actually belongs to line 189

2016-09-26 20:06 UTC, joshdmiller commented on docs/getting_started_guide.md
> +We use [Tape](https://github.com/substack/tape) for testing. Josh is an advocate of test driven development, but you are by no means obligated to do so. You should, however, write tests before submit
How about "We are advocates for test driven development"?

2016-09-26 20:07 UTC, joshdmiller requested changes
A few minor changes...

2016-09-26 20:20 UTC, sethmerrick commented
Done.

2016-09-27 22:03 UTC, joshdmiller commented
@sethmerrick This supersedes #59, right?

2016-09-27 22:20 UTC, sethmerrick commented
@joshdmiller Correct. Best way to indicate supercedence?

2016-09-28 15:36 UTC, sethmerrick commented
@joshdmiller I show pending requested changes and incomplete ci checks here, but do not see any further action I can take. Let me know if there's something I should do to re-trigger circleci.

2016-09-28 18:51 UTC, joshdmiller commented
@sethmerrick Yeah, the test failure is a CircleCI problem. I'm going to move this into "Done" to merge when that problem has been resolved.

2016-09-28 18:51 UTC, joshdmiller approved these changes

2016-09-28 18:53 UTC, sethmerrick commented
👍

2016-09-30 16:33 UTC, merged